version: '3'

services:
  django_web:
    restart: always
    build: .
    container_name: django
    ports:
      - "8000:8000"
    environment:
      DEBUG: "true"
      DB_ENGINE: django.db.backends.mysql
      DB_NAME: p8_mysql_group_db
      DB_USER: user
      DB_PASSWORD: 1
      DB_HOST: mysql
      DB_PORT: 3306

    depends_on:
      - mysql
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

#  postgres:
#    restart: always
#    image: postgres:alpine
#    container_name: p8_pg_db
#    environment:
#      POSTGRES_DB: p8_postgres_group_db
#      POSTGRES_PASSWORD: 1
#    ports:
#      - "5432:5432"
#    volumes:
#      - pg_data:/var/lib/postgresql/data/

  mysql:
    restart: always
    image: mysql:8.0.30-debian
    container_name: p8_mysql_db
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=1
    volumes:
      - my_data:/var/lib/mysql

#  elasticsearch:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
#    volumes:
#      - els_data:/usr/share/elasticsearch/data

volumes:
#  pg_data:
  my_data:
#  els_data:
